### ISSUE TITLE
VAST Support for other adservers than Google's

### ISSUE THREAD

**Issue by Marabyte** [videogular/bower-videogular-ima-ads#2]
Hi!
Do you have any documentation on supporting different adservers?
To enable/disable preroll or midroll and other magic stuff.

Cheers!

**Comment by 2fdevs** [comment]
Hi,

No, we don't have it, but if you're using a VAST document it should work.

Google IMA haves support for VAST 2.0 and VAST 3.0, so if you have a VAST document, just point to that url with your custom ads and that's all.
