### ISSUE TITLE
How to specify pre-roll vs post-roll, documentation is lacking

### ISSUE THREAD

**Issue by jpike88** [videogular/bower-videogular-ima-ads#3]
I've managed to get preroll working with a static VAST XML template:

`<?xml version="1.0" encoding="UTF-8"?>
<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0">
 <Ad id="697203496">
  <InLine>
   <AdSystem>GDFP</AdSystem>
   <AdTitle>External NCA1C1L1 Linear Inline</AdTitle>
<Creatives>
<Creative sequence="1" id="7969">
<Linear>
<Duration></Duration>
<TrackingEvents>
</TrackingEvents>
<VideoClicks>
</VideoClicks>
<MediaFiles>
<MediaFile delivery="progressive" bitrate="600" width="640" height="480" type="video/mp4">
<![CDATA[
http://cdn.liverail.com/adasset4/1331/229/7969/me.mp4
]]>
</MediaFile>
</MediaFiles>
</Linear>
</Creative>
<Creative sequence="2" id="79639">
<Linear>
<Duration></Duration>
<TrackingEvents>
</TrackingEvents>
<VideoClicks>
</VideoClicks>
<MediaFiles>
<MediaFile delivery="progressive" bitrate="600" width="640" height="480" type="video/mp4">
<![CDATA[
http://cdn.liverail.com/adasset4/1331/229/7969/me.mp4
]]>
</MediaFile>
</MediaFiles>
</Linear>
</Creative>
</Creatives>
  </InLine>
 </Ad>
</VAST>`

My config ads object looks like this:

`ads: {
                        adTagUrl: "http://!!!VAST-XML-URL-GOES-HERE!!!",
                        skipButton: null
                    }`

Preroll works. But I have absolutely no idea how to make the post roll kick in. The documentation is non-existent for this plugin and going to the Google IMA Ads website hasn't helped.

What can I do? I basically want to serve two specific static video files as preroll and post roll every time the video player plays. For something really simple this VAST stuff is driving me nuts.

**Comment by Elecash** [comment]
This is our VAST example file, which is a public file from double click that haves `preroll`, `midroll` and `post-roll`.

http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<vmap:VMAP xmlns:vmap="http://www.iab.net/videosuite/vmap" version="1.0">
 <vmap:AdBreak timeOffset="start" breakType="linear" breakId="preroll">
  <vmap:AdSource id="preroll-ad-1" allowMultipleAds="false" followRedirects="true">
   <vmap:AdTagURI templateType="vast3"><![CDATA[http://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=preroll&pod=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=&video_doc_id=short_onecue&cmsid=496]]></vmap:AdTagURI>
  </vmap:AdSource>
 </vmap:AdBreak>
 <vmap:AdBreak timeOffset="00:00:15.000" breakType="linear" breakId="midroll-1">
  <vmap:AdSource id="midroll-1-ad-1" allowMultipleAds="false" followRedirects="true">
   <vmap:AdTagURI templateType="vast3"><![CDATA[http://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=midroll&pod=2&mridx=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=&video_doc_id=short_onecue&cmsid=496]]></vmap:AdTagURI>
  </vmap:AdSource>
 </vmap:AdBreak>
 <vmap:AdBreak timeOffset="end" breakType="linear" breakId="postroll">
  <vmap:AdSource id="postroll-ad-1" allowMultipleAds="false" followRedirects="true">
   <vmap:AdTagURI templateType="vast3"><![CDATA[http://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=postroll&pod=3&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=&video_doc_id=short_onecue&cmsid=496]]></vmap:AdTagURI>
  </vmap:AdSource>
 </vmap:AdBreak>
</vmap:VMAP>
```

Please, next time use the correct repository to post your issues, this is only for distribution. Use this:
https://github.com/videogular/videogular

**Comment by jpike88** [comment]
Thanks I will link this to the main repo asking for more extensive documentation

**Comment by Elecash** [comment]
Sure! :+1:
