### ISSUE TITLE
Extending Directive

### ISSUE THREAD

**Issue by esuveyke** [videogular/bower-videogular-ima-ads#4]
Im looking to extend the directive and looking for an elegant way to do so.  Using a simple example of adding an event handler.  My other case is much more intensive.  But would like to start here:

Given "scope.onAdsManagerLoaded" @line 120 ish...

```
            scope.onAdsManagerLoaded = function onAdsManagerLoaded(adsManagerLoadedEvent) {                    
                scope.show();
                adsManager = adsManagerLoadedEvent.getAdsManager(API.mediaElement[0]);

              // START ADDITION
                adsManager.addEventListener(google.ima.AdEvent.Type.LOADED,
                    function(adEvent){
                        console.log("adData",adEvent.getAd());
                    }
                );
              // END ADDITION

                scope.processAdsManager(adsManager);
            };
```

**Comment by Elecash** [comment]
It looks fine for me, what's the problem?

**Comment by esuveyke** [comment]
i was looking to extend the directive itself.  we went ahead and just modified it directly.

ty - you addressed in the email

**Comment by Elecash** [comment]
You're welcome :smile:
